
const repo="OpenMakerProjects/"+load("entries")[id-1].slug,branch="automation/complete-"+String(id).padStart(3,"0")+"-20261010",get=async p=>{const r=await tools.mcp__codex_apps__github_fetch({url:"https://api.github.com/repos/"+repo+p});if(!r.structuredContent?.content)throw Error(JSON.stringify(r));return JSON.parse(r.structuredContent.content);};
const pause=async msg=>{notify(msg);await new Promise(r=>setTimeout(r,30000));};
let runs,decoder;
for(let i=0;i<40;i++){runs=(await get("/actions/runs?head_sha="+load("head"+id))).workflow_runs;decoder=runs.find(x=>x.name.includes("Decode"));if(decoder?.status==="completed")break;await pause("ID"+id+" decoded-image full gates still running.");}
if(decoder?.conclusion!=="success")throw Error("Decoder "+decoder?.id+" failed");
const branches=await get("/branches");const ref=branches.find(x=>x.name===branch);if(!ref)throw Error("branch missing");const c=await get("/git/commits/"+ref.commit.sha),tree=await get("/git/trees/"+c.sha+"?recursive=1");
if(!tree.tree.some(x=>x.path==="docs/images/project-overview.png")||tree.tree.some(x=>/\.b64|image-staging/.test(x.path)))throw Error("image tree incomplete");
const files={...(load("repair"+id)||{}),"docs/validation-results.md":"# Actual cloud validation\n\nOn 2026-10-10 IST, image recovery run "+decoder.id+" passed its full host/artifact/target gates on decoded commit "+c.sha+" after lossless PNG SHA256/CRC/dimension verification and transport cleanup.\n\nFinal push and PR workflows independently validate "+tests+" on the exact final head before merge. This commit triggers those final checks; their URLs and results are recorded in durable run state.\n\nPhysical hardware and live connectivity tests were not performed.\n"};
const t=(await tools.mcp__codex_apps__github_create_tree({repository_full_name:repo,base_tree_sha:c.tree.sha,tree_elements:Object.entries(files).map(([path,content])=>({path,mode:"100644",type:"blob",content}))})).structuredContent.sha;
const h=(await tools.mcp__codex_apps__github_create_commit({repository_full_name:repo,parent_sha:c.sha,tree_sha:t,message:"Record decoded-source results and trigger final host/target checks"})).structuredContent.sha;
await tools.mcp__codex_apps__github_update_ref({repository_full_name:repo,branch_name:branch,sha:h,expected_sha:c.sha,force:false});store("final"+id,h);
for(let i=0;i<40;i++){runs=(await get("/actions/runs?head_sha="+h)).workflow_runs.filter(x=>x.event==="push"&&["Validate project","Completion gates"].includes(x.name));if(runs.length>=2&&runs.every(x=>x.status==="completed"))break;await pause("ID"+id+" final push host/target gates running.");}
if(runs.length!==2||!runs.every(x=>x.conclusion==="success"&&x.head_sha===h))throw Error("Push gates failed "+JSON.stringify(runs.map(x=>({id:x.id,name:x.name,conclusion:x.conclusion}))));
const prs=await get("/pulls?state=all");if(prs.some(x=>x.merged_at))throw Error("prior merged PR requires reconcile");let pr=prs.find(x=>x.head.ref===branch&&x.state==="open");
if(!pr)pr=(await tools.mcp__codex_apps__github_create_pull_request({repository_full_name:repo,head:branch,base:"main",title:"Complete "+load("entries")[id-1].title+" educational prototype",body:"Implements project-specific source/configuration, strong README, precise circuit SVG, full MIT license, original losslessly verified PNG, and meaningful host/target gates. Both push checks passed on "+h+". Validation includes "+tests+". Physical hardware and live connectivity have not been tested. Merge requires both PR checks green on this exact head."})).structuredContent;
store("pr"+id,pr.number);
for(let i=0;i<40;i++){runs=(await get("/actions/runs?head_sha="+h)).workflow_runs.filter(x=>["push","pull_request"].includes(x.event)&&["Validate project","Completion gates"].includes(x.name));if(runs.length>=4&&runs.every(x=>x.status==="completed"))break;await pause("ID"+id+" PR "+pr.number+" exact-head checks running.");}
if(runs.length!==4||!runs.every(x=>x.conclusion==="success"&&x.head_sha===h))throw Error("PR gates failed "+JSON.stringify(runs.map(x=>({id:x.id,name:x.name,event:x.event,conclusion:x.conclusion}))));
pr=await get("/pulls/"+pr.number);if(pr.head.sha!==h||!pr.mergeable||pr.state!=="open")throw Error("PR state changed");store("ready"+id,{head:h,pr:pr.number,tests,runs:runs.map(x=>({id:x.id,name:x.name,event:x.event,head:x.head_sha,conclusion:x.conclusion}))});notify("ID"+id+" PR "+pr.number+" is ready: all four exact-head checks successful. Head "+h);return load("ready"+id);
