const repo="OpenMakerProjects/"+load("entries")[id-1].slug,branch="automation/complete-"+String(id).padStart(3,"0")+"-20261010",tr=load("tr"+id);
const get=async p=>JSON.parse((await tools.mcp__codex_apps__github_fetch({url:"https://api.github.com/repos/"+repo+p})).structuredContent.content);
let c=await get("/git/commits/"+load("head"+id)),base=c.tree.sha,parent=c.sha;let elements=[];let i=0;
for(;i<tr.chunks.length;i+=4){const batch=tr.chunks.slice(i,i+4).map((x,j)=>({path:"docs/image-staging/"+tr.manifest.chunks[i+j],mode:"100644",type:"blob",content:typeof x==="string"?x:x.content}));const r=await tools.mcp__codex_apps__github_create_tree({repository_full_name:repo,base_tree_sha:base,tree_elements:batch});if(r.isError||!r.structuredContent?.sha)throw Error("image tree "+JSON.stringify(r));base=r.structuredContent.sha;
 if((i+4)%16===0||i+4>=tr.chunks.length){const nc=(await tools.mcp__codex_apps__github_create_commit({repository_full_name:repo,parent_sha:parent,tree_sha:base,message:"Checkpoint bounded original PNG transport "+Math.min(i+4,tr.chunks.length)+"/"+tr.chunks.length})).structuredContent.sha;
 await tools.mcp__codex_apps__github_update_ref({repository_full_name:repo,branch_name:branch,sha:nc,expected_sha:parent,force:false});parent=nc;store("head"+id,parent);notify("ID"+id+" image staging "+Math.min(i+4,tr.chunks.length)+"/"+tr.chunks.length+" committed.");}
}
const tree=await get("/git/trees/"+base+"?recursive=1"),staged=tree.tree.filter(x=>x.path.startsWith("docs/image-staging/")&&x.type==="blob");if(staged.length!==tr.chunks.length)throw Error("staging count");
elements=staged.flatMap(x=>[{path:"docs/images/"+x.path.split("/").pop(),mode:"100644",type:"blob",sha:x.sha},{path:x.path,mode:"100644",type:"blob",sha:null}]);elements.push({path:"docs/images/project-overview.manifest.json",mode:"100644",type:"blob",content:JSON.stringify(tr.manifest,null,2)+"\n"});
const nt=(await tools.mcp__codex_apps__github_create_tree({repository_full_name:repo,base_tree_sha:base,tree_elements:elements})).structuredContent.sha,nc=(await tools.mcp__codex_apps__github_create_commit({repository_full_name:repo,parent_sha:parent,tree_sha:nt,message:"Activate complete original PNG text transport for lossless cloud decoding"})).structuredContent.sha;
await tools.mcp__codex_apps__github_update_ref({repository_full_name:repo,branch_name:branch,sha:nc,expected_sha:parent,force:false});store("head"+id,nc);notify("ID"+id+" image decoder and full completion gates triggered at "+nc);
